title: Hanjun's Blog
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://hanjun0126.github.io

aux_links:
  GitHub: https://github.com/hanjun0126
